# Generated by Django 5.0.7 on 2024-09-16 03:43

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cartorder_address_cartorder_city_cartorder_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, length=5, max_length=20, null=True, prefix='SKU'),
        ),
    ]
